### ISSUE TITLE
Get error message: Prop `className` did not match, when rendering page or refreshing page

### ISSUE THREAD

**Issue by jkrvivian** [TangleID/TangleID#13]
This problem happens when refreshing page and sometimes  happens when rendering page.
Full error message:
`Warning: Prop `className` did not match. Server: “MuiButtonBase-root-61 MuiIconButton-root-55 MuiIconButton-colorInherit-56 PersistentDrawer-menuButton-1075” Client: “MuiButtonBase-root-61 MuiIconButton-root-55 MuiIconButton-colorInherit-56 PersistentDrawer-menuButton-8” warning.js:33`

![](https://i.imgur.com/6vWvtej.png)

**Comment by ender503** [comment]
I think this problem is caused by the Next.js, and it's related to this [issue](https://github.com/styled-components/styled-components/issues/1239).

**Comment by jserv** [comment]
Only valid for V1 API implementation.
