### ISSUE TITLE
Add document to describe DID methods implementation

### ISSUE THREAD

**Issue by ender503** [TangleID/TangleID#136]
In [DID Method Registry](https://w3c-ccg.github.io/did-method-registry/), each DID method has described how they implement the DID methods, so we'll need to add a document to describe how TangleID implement the DID methods

**Comment by ender503** [comment]
[TangleID DID Specification (WIP)](https://hackmd.io/dD1Vn_jWT6SXcUiryH9BQQ)

**Comment by wusyong** [comment]
There are some reminders need to be checked before the PR:

- Check the formatting of your ABNF
- Specify what happens in the Delete operation
- Finish the Security and Privacy Consideration sections (Too many early submissions left these blank.)

**Comment by wusyong** [comment]
Closed by #141
