### ISSUE TITLE
Failed to install "ursa" module when working with nodejs 10

### ISSUE THREAD

**Issue by ender503** [TangleID/TangleID#14]
This problem is related to this [issue](https://github.com/JoshKaufman/ursa/issues/167).
It has been fixed in upstream, but we need to wait for package updated.

**Comment by ender503** [comment]
The problem is fixed in the Github repository, but the `ursa` NPM package doesn't update since two years. 

@HexRabbit, since we only use this `ursa` to create key pairs, maybe we could change another NPM package? 😃 
 * [node-rsa](https://www.npmjs.com/package/node-rsa)
 * [node-forge](https://www.npmjs.com/package/node-forge)  this package contains cryptographic tools written in Javascript.

**Comment by bw-changeup** [comment]
I believe I'm having a similar, if not the same, problem

`npm -v
6.1.0

node -v
10.4.1`

Attaching logs here, I believe it's an issue compiling ursa:
https://hackmd.io/s/HJytVZnM7

I'm trying to install on a bitnami node server on gcp, just cloned and tried to run npm install.

LMK if I can help somehow, thanks

**Comment by jserv** [comment]
Defer to @HexRabbit for key generator.

**Comment by HexRabbit** [comment]
@bw-changeup 
Have switched from `ursa` to `node-forge` package, should work fine on nodejs 10.x now.
