### ISSUE TITLE
Use MAMv1 to replace the tic.api.js

### ISSUE THREAD

**Issue by ender503** [TangleID/TangleID#169]
In the current version of TangleID, we are using the `tic.api.js` to register the identifier on the Tangle, it will create 3 MAM channels and use the profile channel to store the DID document. 

To improve the speed of identifier registration speed, we'll try to use the [iotaledger/mam.client.js](https://github.com/iotaledger/mam.client.js/) and create a single channel which store the DID document information.

There is a newer version of [MAM](https://github.com/iotaledger/entangled/tree/develop/mam), to distinguish the different version of MAMs, we'll considering to modify the DID schema like the following approaches:

1. Use different method name(Recommend)

```
## MAM
did:tangle-legacy:{Channel Root}
## MAM(New)
did:tangle:{Channel Root}
```

2. Use subnamespace
```
## MAM
did:tangle:{Channel Root}:mam-legacy
## MAM(New)
did:tangle:{Channel Root}:mam
```

**Comment by jserv** [comment]
Never call it "did:tangle-legacy". Instead, unify "did:tangle" all the time.

**Comment by jserv** [comment]
We might mix MAM-Legacy and MAM for the sake of different shape of product requirement, and it is crucial to unify the schema.

**Comment by ender503** [comment]
After discussing with @jserv, we will use this schema `did:tangle{channel_root}-` (trailing dash) for MAMv1, and use `did:tangle{channel_root}` (without  trailing dash) for MAMv2.
