### ISSUE TITLE
Build failure on macOS High Sierra

### ISSUE THREAD

**Issue by jserv** [TangleID/TangleID#18]
At present, TangleID depends on ursa, which can not get build on macOS High Sierra.

Error messages:
```
$ npm install
...
  CXX(target) Release/obj.target/ursaNative/src/ursaNative.o
../src/ursaNative.cc:389:13: error: member access into incomplete type 'RSA' (aka 'rsa_st')
    obj->rsa->n = BN_bin2bn(data_n, n_length, NULL);
            ^
/Users/apple/.node-gyp/10.3.0/include/node/openssl/ossl_typ.h:110:16: note: forward declaration of 'rsa_st'
typedef struct rsa_st RSA;
               ^
../src/ursaNative.cc:390:13: error: member access into incomplete type 'RSA' (aka 'rsa_st')
    obj->rsa->e = BN_bin2bn(data_e, e_length, NULL);
```

**Comment by ender503** [comment]
This problem related to Issue #14, the `ursa` package build failed with newer node.

You can change the node to the stable version(v8.11.2) with `nvm` for now.
```
$ brew install nvm
$ nvm use stable
$ npm install
```
The `ursa` is updated too slow on [npm]([ursa - npm](https://www.npmjs.com/package/ursa)), maybe we could use the latest version on Github or find another replacement. 🤔

**Comment by jserv** [comment]
Regarded as duplication of #14
