### ISSUE TITLE
Consolidate node configurations 

### ISSUE THREAD

**Issue by jserv** [TangleID/TangleID#35]
At first glance, at least two source files specifies default node:
* `utils/cert.js:var` defaultNode = "http://node.deviceproof.org:14265";
* `utils/mamUtils.js:var` iota = new IOTA({ provider: 'http://node.deviceproof.org:14265' })

We shall avoid hardcoded initialization of each IOTA object. Instead, system-wide configuration file can be used accordingly.

**Comment by HexRabbit** [comment]
@ender503 
Now we have two source of api calls: TangleID api and iota library api.
In `cert.js` and `mamUtils.js` we need to use iota library api, not TangleID api.
Although we need to consolidate these two in future, but for now maybe we need to add a new variable for iota lib api server in `.env` file?

**Comment by jserv** [comment]
In continuation of @ender503's idea, we shall always avoid using general names to specify dedicated items. In this case, `BACKEND` is a confusing example.

The major motivation of `iota-swarm-node` is to accelerate Tangle-based applications, and it will be renamed to `tangle-accelerator` once its hardware accelerator is ready. We can refer to [CarrIOTA Nelson](https://gitlab.com/semkodev/nelson.cli) and check how it configures:
* apiPort = 18600
* apiHostname = 127.0.0.1

`TANGLEID_API_PROVIDER` is too long to me. How about `API_HOST` and `IRI_HOST`?

**Comment by ender503** [comment]
It looks better. 👍
