### ISSUE TITLE
Degradation of web rendering at first load time

### ISSUE THREAD

**Issue by jkrvivian** [TangleID/TangleID#38]
Now, TangleID takes really a long time loading each page.
For a better user experience, we should try decreasing the loading time.

TangleID is a server-side rendering APP.
The purpose of server-side rendering service is to speed up page loading speed.
After reading some discussions, I found out that we've been loading webpage on both server and client side. The most crucial part is getting information via calling TangleID APIs, which is really time costing.

**Comment by jserv** [comment]
Only valid for V1 API implementation.
