### ISSUE TITLE
Set up continuous integration

### ISSUE THREAD

**Issue by jserv** [TangleID/TangleID#41]
Continuous integration (CI) is the practice of merging all developer working copies to a shared mainline several times a day. When embarking on a change, a developer takes a copy of the current code base on which to work. As other developers submit changed code to the source code repository, this copy gradually ceases to reflect the repository code. Not only can the existing code base change, but new code can be added as well as new libraries, and other resources that create dependencies, and potential conflicts.

Expected output:
1. Ensure validate flow with CI;
2. Trigger specific test items upon each change;
3. Track reported regressions.

**Comment by ender503** [comment]
I'll handle this issue after PR #34 merged. 👍

**Comment by ender503** [comment]
We will check the following items with CI.
- [ ] Dependencies test (npm install)
- [ ] Coding style check (npm run eslint)
- [ ] Unit test (npm run test)
