### ISSUE TITLE
Use undefined variable in tools.js

### ISSUE THREAD

**Issue by ender503** [TangleID/TangleID#48]
The local variable `Iota` is undefined in verify(), verifyHash() functions. [[Link]](https://github.com/TangleID/TangleID/blob/9e6597a060ed3c98a11f2f2893b2949e67e57412/utils/tools.js#L32)
Since verify(), verifyHash() functions are not used by others, could we remove them? 🤔

**Comment by jserv** [comment]
Please go for code cleanup.

**Comment by HexRabbit** [comment]
@ender503 That's my mistake. You can clean those functions.

**Comment by ender503** [comment]
It's ok, let us clean up these codes. 😃
