### ISSUE TITLE
Automate API documentation generation

### ISSUE THREAD

**Issue by jserv** [TangleID/TangleID#56]
Good documentation accelerates development and consumption, and reduces the money and time that would otherwise be spent answering support calls. Documentation is part of the overall user experience, and is one of the biggest factors for increased API growth and usage.

It would be great if we can introduce documentation generator for [OpenAPI/Swagger](https://swagger.io/docs/specification/about/).

**Comment by jserv** [comment]
Blocked by #54

**Comment by jserv** [comment]
@ender503, is time to close?

**Comment by ender503** [comment]
It could be closed. 👍
