### ISSUE TITLE
Move TangleID API reference manual to GitHub Pages

### ISSUE THREAD

**Issue by jserv** [TangleID/TangleID#59]
TangleID reference manual was collaborated via Google Docs, and it would be effective if we can move it to GitHub Wiki for hosting and community visibility.

Expected output:
* Wiki pages mentioning each API call along with informative reference manual;
* File `README.md` indicating links to corresponding Wiki pages;

**Comment by jserv** [comment]
Related issue: #56

**Comment by yillkid** [comment]
I have revised some API command and description, @spin could you checking your part and forzen the document for preparing to move?

**Comment by jserv** [comment]
Per the discussions at July, we would move forward to GitHub Pages, which can be activated by `gh-pages` branch.

**Comment by jserv** [comment]
It is online: https://tangleid.github.io/docs/
