### ISSUE TITLE
Remove obsolete middleware or dependencies

### ISSUE THREAD

**Issue by ender503** [TangleID/TangleID#60]
The redux middleware provides a third-party extension point between dispatching an action, and the moment it reaches the reducer.

The `api.js` middleware is designed to invoke the API call if the action contains `CALL_API` key.
It is obscure to call the API with this middleware, so we are engaged to eliminate such facility.

**Comment by ender503** [comment]
Blocked by #46.

**Comment by jserv** [comment]
Only valid for V1 API implementation.
