### ISSUE TITLE
Internal server error 500 after multiple new_user request

### ISSUE THREAD

**Issue by HexRabbit** [TangleID/TangleID#8]
After creating user in `New User` page, then go back to `New User` page by clicking the `New User` button in the sidebar, when I try to create another one it has no response but shows `internal server error 500` in the web console. Check the json data of the POST request, you will find that the information, such as username, won't be included.
But if you go back to `Users` page first then switch back to `New User`, you can create a user as usual.

**Comment by jserv** [comment]
You shall improve the descriptions in advance.
Reference: [How to write bug report](https://geteasyqa.com/qa/write-bug-report/)

**Comment by jserv** [comment]
@ender503, your turn for resolving this issue.

**Comment by ender503** [comment]
Hi @HexRabbit, 

I reproduce the issue with following steps.
1. Go to “New User” page.
2. Input the “first name” and  “last name” fields.
3. Click the SEND button to register a new user.
4. Open the drawer and click “New User” button.
5. Input the “first name” and  “last name” fields.
6. Click the SEND button again.
7. Then we can find out the error message in browser’s console.
```
POST http://localhost:3000/api/proxy/ 500 (Internal Server Error)
```

In the Chrome DevTools’s network tab, it give us more detail.

Here is the request.
```
{
  "command": "new_user",
  "pk": "...",
  "uuid": "...",
  "signature": ""
}
```

And response message.
```
KeyError at /api/api/proxy/
'first_name'
Request Method:	POST
Request URL:	http://localhost:3000/tangleid_backend/api/api/proxy/
```

It look like the `first_name` is missing in the POST request field.
I’ll try to resolve this problem. 👍
