### ISSUE TITLE
Replace RSA with NTRU for restricted or private MAM 

### ISSUE THREAD

**Issue by jserv** [TangleID/TangleID#84]
When using restricted or private MAM between two parties first a key exchange needs to take place. The root (in private) and root and side key (restricted) of the MAM channel needs to be communicated. 

The idea is using NTRUEncrypt for IOTA and generate key pairs from an IOTA seed. NTRU stands for Nth Degree Truncated Polynomial Ring. This refers to the underlying calculation that needs to be done for decryption and encryption. This is assumed to be difficult and quantum computing safe.

Compared to RSA, NTRU is faster and uses less memory. NTRU keys are longer.

Reference: [Sharing smart meter measurements with consent on IOTA](https://github.com/Alliander/decentralized-auth/blob/master/docs/technologies.md)

**Comment by jserv** [comment]
Related: #64

**Comment by ender503** [comment]
I make an example code for encrypt the MAM message with NTRU in this [repository](https://github.com/ender503/ntru/blob/master/tests/mam.test.js).

**Comment by jserv** [comment]
Please evaluate the feasibility to adapt TangleID existing codebase for NTRU-based messaging.

**Comment by ender503** [comment]
Since we are moving to MAMv2, this would be discussed in Tangle Accelerator.
