### ISSUE TITLE
Use MAM to Send the Verifiable Claims

### ISSUE THREAD

**Issue by ender503** [TangleID/TangleID#85]
In the TangleID v1, save the verifiable claim in the IOTA Transaction, but it could not be revoked.

In the context of Masked Authenticated Message (MAM), the messages are chained together, so the issuer can revoke by attaching new MAM message to MAM channel, and the third-party can get the latest information about this claim.

![image](https://user-images.githubusercontent.com/1849431/51584763-a4b8f280-1f11-11e9-88d1-e975ec6fbf4c.png)

**Comment by jserv** [comment]
Instead of anchoring `TangleID v1`, we would call it `Tanagle-legacy` to avoid the ambiguity while referring to software release.
