### ISSUE TITLE
Utilities for generating the Credential/Claim

### ISSUE THREAD

**Issue by ender503** [TangleID/TangleID#88]
Related: #85

**Comment by jserv** [comment]
Per discussion on Feb 14, we need relevant descriptive materials.

**Comment by ender503** [comment]
I summarize the changes to the W3C verifiable credential specification into this presentation([Link](https://docs.google.com/presentation/d/1jZnAMbVIunMWq5pMzDASLKgSHTA-BFhAUUNm06C-Uac/edit))
